'use client';

import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {ArrowRight,ArrowUpRight,Zap,Check,Search,Globe,MessageSquare,Store,Home,ChevronDown,Copy,LoaderCircle,ShieldCheck,Code2,RefreshCw,Mail,CheckCircle2,ArrowLeft} from 'lucide-react';
import type {Workspace,Surface,Receipt,ApiEnvelope} from '@/lib/types';

async function api<T>(path:string,body?:unknown,method='POST'):Promise<T>{
  const r=await fetch(path,{method:body===undefined?'GET':method,headers:{'Content-Type':'application/json'},...(body!==undefined?{body:JSON.stringify(body)}:{})});
  const data=await r.json() as ApiEnvelope<T>;
  if(!data.ok)throw new Error(data.error.message);
  return data.data;
}
function Brand(){return <Link className="brand" href="/" aria-label="Agent Power Up home"><span className="brand-mark"><Zap size={22} fill="currentColor"/></span><span>power up<span className="brand-period">.</span></span></Link>}
function Busy(){return <LoaderCircle className="spin" size={20} aria-hidden="true"/>}
function Status({live,children}:{live?:boolean;children:React.ReactNode}){return <span className={live?'status live':'status'}>{live&&<Check size={14} aria-hidden="true"/>}{children}</span>}

export function Landing(){
 const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 async function start(){setBusy(true);setError('');try{const data=await api<{recoveryKey?:string}>('/api/free-start',{});if(data.recoveryKey)sessionStorage.setItem('apu-recovery',data.recoveryKey);window.location.href='/builder'}catch(e){setError((e as Error).message);setBusy(false)}}
 return <div className="welcome"><header className="app-header"><Brand/><Link className="text-button" href="/builder">Your business <ArrowUpRight size={18}/></Link></header><main className="welcome-main"><span className="eyebrow">AGENT POWER UP · FREE FOR LOCAL BUSINESSES</span><h1>Your business.<br/><span>Ready for agents.</span></h1><p>Give agents a way to find your services and send you real requests. Connect your website. Check your details. See it work.</p><button className="button primary" disabled={busy} onClick={start}>{busy?<Busy/>:<>Start free <ArrowRight size={20}/></>}</button><span className="welcome-note">No card. No sales call.</span>{error&&<p className="error" role="alert">{error}</p>}<div className="value-line"><span><Search size={20}/>Share your services</span><span><MessageSquare size={20}/>Receive requests</span><span><CheckCircle2 size={20}/>Verify a real result</span></div></main><footer className="welcome-footer">Your own hosted agent node. Open connections. No guaranteed partner listings.</footer></div>
}

type Tab='Home'|'Requests'|'Business';
export function Dashboard({initialWorkspace}:{initialWorkspace?:Workspace}={}){
 const[w,setW]=useState<Workspace|null>(initialWorkspace??null);const[loading,setLoading]=useState(!initialWorkspace);const[tab,setTab]=useState<Tab>('Home');
 const[busy,setBusy]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');const[url,setUrl]=useState('');const[edit,setEdit]=useState<Partial<Surface>>(initialWorkspace?.business.surface??{});
 const[query,setQuery]=useState('');const[key,setKey]=useState('');const[recovery,setRecovery]=useState('');const[copied,setCopied]=useState('');const[result,setResult]=useState<Receipt|null|undefined>(undefined);
 async function load(){const data=await api<Workspace>('/api/workspace');setW(data);setEdit(data.business.surface);return data}
 useEffect(()=>{setRecovery(sessionStorage.getItem('apu-recovery')||'');load().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 async function run(label:string,fn:()=>Promise<unknown>,message=''){setBusy(label);setError('');setNotice('');try{await fn();await load();setNotice(message)}catch(e){setError((e as Error).message);try{await load()}catch{}}finally{setBusy('')}}
 async function copy(value:string,id:string){try{await navigator.clipboard.writeText(value);setCopied(id);setTimeout(()=>setCopied(''),2500)}catch{setError('Copy is unavailable. Select and copy the text below.')}}
 function navigate(next:Tab){setTab(next);setError('');setNotice('')}
 function field(name:keyof Surface,label:string,type='text'){return <label className="field">{label}<input type={type} required={name==='name'} value={String(edit[name]??'')} onChange={e=>setEdit({...edit,[name]:e.target.value})}/></label>}
 if(loading)return <main className="center-screen"><Brand/><Busy/><p>Opening your business…</p></main>;
 if(!w)return <main className="center-screen"><Brand/><h1>Let’s get you connected.</h1><p>{error||'Create your free business workspace.'}</p><Link className="button primary" href="/">Start free <ArrowRight size={20}/></Link><Link className="text-button" href="/access">Recover your business</Link></main>;
 const b=w.business;const imported=!!b.surface.importedAt;const published=b.published;const live=w.funnel.callableSucceeded;
 const latest=result===undefined?(b.receipts.find(r=>r.action==='find')??null):result;
 const returned=latest?.action==='find'?latest.result.business as Surface|undefined:undefined;
 const successfulFinds=b.events.filter(e=>e.name==='callable_succeeded'&&e.action==='find').length;
 const setupStep=!imported?1:!published?2:3;
 const navItems=[{name:'Home' as Tab,icon:Home},{name:'Requests' as Tab,icon:MessageSquare},{name:'Business' as Tab,icon:Store}];
 const nav=<nav className="main-nav" aria-label="Main navigation">{navItems.map(({name,icon:Icon})=><button key={name} className={tab===name?'nav-button active':'nav-button'} onClick={()=>navigate(name)} aria-current={tab===name?'page':undefined}><Icon size={20}/><span>{name}</span>{name==='Requests'&&b.quotes.length>0&&<span className="nav-badge">{b.quotes.length}</span>}</button>)}</nav>;
 async function find(){setResult(null);await run('find',async()=>{const receipt=await api<Receipt>('/api/call',{action:'find',input:{query:query.trim()||b.surface.name}});setResult(receipt)})}
 return <div className="product"><a className="skip-link" href="#main">Skip to content</a><header className="app-header"><Brand/>{nav}<span className="account-label">Free workspace</span></header><main className="workspace" id="main"><div className="page-title"><div><span className="eyebrow">{b.surface.name||'YOUR BUSINESS'}</span><h1>{tab==='Home'?(live?'You’re connected.':'Let’s power you up.'):tab==='Requests'?'Your next opportunity.':'Your business, clearly.'}</h1></div>{published&&<Status live={live}>{live?'Callable live':'Ready to test'}</Status>}</div>
 {error&&<div className="error-banner" role="alert"><strong>That didn’t work.</strong><p>{error}</p>{busy===''&&published&&tab==='Home'&&<button className="text-button" onClick={find}>Try again <RefreshCw size={16}/></button>}</div>}
 {notice&&<p className="notice" role="status"><CheckCircle2 size={18}/>{notice}</p>}
 {tab==='Home'&&<>
  {!published?<section className="focus-card setup"><div className="step-label">STEP {setupStep} OF 3 <span>{imported?'Review your business':'Connect your business'}</span></div><h2>{imported?'Looking good?\nMake it available.':'One connection.\nMore possibilities.'}</h2><p>{imported?'Check the details agents will use before you activate your business.':'Start with your website. We’ll bring in your business details for you to review.'}</p>
  {!imported?<form onSubmit={e=>{e.preventDefault();run('import',()=>api('/api/ingest',{url}))}}><label htmlFor="website">Your business website</label><div className="connect-input"><Globe size={22}/><input id="website" type="url" required placeholder="https://yourbusiness.com" value={url} onChange={e=>setUrl(e.target.value)}/></div><button className="button primary" disabled={!!busy}>{busy==='import'?<Busy/>:<>Connect my business <ArrowRight size={20}/></>}</button><button type="button" className="text-button" onClick={()=>navigate('Business')}>No website? Add your details</button></form>:<><div className="review-business"><span className="business-icon"><Store size={26}/></span><div><strong>{b.surface.name}</strong><span>{b.surface.category||'Local business'}{b.surface.address&&` · ${b.surface.address}`}</span><span>{b.surface.services.length} services · {b.surface.confidence} import confidence</span></div><button className="text-button" onClick={()=>navigate('Business')}>Edit</button></div><button className="button primary" disabled={!!busy} onClick={()=>run('publish',()=>api('/api/publish',{}))}>{busy==='publish'?<Busy/>:<>Activate my business <ArrowRight size={20}/></>}</button></>}
  <div className="setup-progress" aria-label={`Step ${setupStep} of 3`}><span className="done"/><span className={setupStep>=2?'done':''}/><span/></div></section>:<>
   <section className="focus-card proof"><div className="proof-heading"><div><span className="eyebrow">{live?'CHECK YOUR CONNECTION':'ONE LAST STEP'}</span><h2>{live?'See what agents see.':'Let’s see it work.'}</h2><p>Search one of your services. See the real response from your business.</p></div><span className="proof-icon"><Search size={32}/></span></div><form onSubmit={e=>{e.preventDefault();find()}}><label className="sr-only" htmlFor="find-query">Business or service to find</label><div className="search-box"><Search size={22}/><input id="find-query" value={query} onChange={e=>setQuery(e.target.value)} placeholder={b.surface.name||'Your business or service'}/><button className="button primary" disabled={!!busy} aria-label="Run live find request">{busy==='find'?<Busy/>:<><span>Try it</span><ArrowRight size={22}/></>}</button></div><div className="suggestions">{b.surface.services.filter(Boolean).slice(0,3).map((service,i)=><button type="button" key={i} onClick={()=>setQuery(service)}>{service}</button>)}</div></form>
   {latest&&returned&&<div className="real-result" role="status"><div className="result-label"><CheckCircle2 size={18}/> Found by your agent node <span>{latest.environment}</span></div><h3>{returned.name}</h3><p>{returned.description||returned.category}</p>{returned.address&&<span>{returned.address}</span>}<div className="service-list">{returned.services.map((s,i)=><span key={i}>{s}</span>)}</div><details><summary>View confirmation <ChevronDown size={16}/></summary><code>{latest.id}</code><span>{new Date(latest.createdAt).toLocaleString()}</span></details></div>}
   </section><div className="outcome-row"><div><span>Successful FIND calls</span><strong>{successfulFinds}</strong><small>Includes your own checks</small></div><button onClick={()=>navigate('Requests')}><span>Requests received <ArrowUpRight size={18}/></span><strong>{b.quotes.length}</strong><small>Open your inbox</small></button></div></>}
  <section className="connections"><div className="section-heading"><h2>What your business can do</h2></div>{w.powerUps.filter(p=>p.id==='find'||p.id==='quote').map(p=><div className="connection-row" key={p.id}><span className="connection-icon">{p.id==='find'?<Search size={24}/>:<MessageSquare size={24}/>}</span><div><h3>{p.id==='find'?'Be found':'Receive quote requests'}</h3><p>{p.id==='find'?'Share your services and business details.':'New requests arrive in your inbox.'}</p></div><Status live={p.status==='live'}>{p.status}</Status></div>)}<details className="more-connections"><summary>More connections <span>Square, ChatGPT, Google <ChevronDown size={16}/></span></summary>{w.powerUps.filter(p=>p.id!=='find'&&p.id!=='quote').map(p=><div className="connection-row" key={p.id}><div><h3>{p.name}</h3><p>{p.reason||p.description}</p></div><Status live={p.status==='live'}>{p.status}</Status></div>)}<p className="fine-print">A working node does not guarantee discovery on partner platforms.</p></details></section>
  {recovery&&<details className="recovery-reminder"><summary><ShieldCheck size={19}/> Save your recovery key <ChevronDown size={16}/></summary><p>This is how you reopen your business on another device. Keep it private; we can’t email it to you.</p><button className="button secondary" onClick={()=>copy(recovery,'recovery')}>{copied==='recovery'?'Copied':'Copy recovery key'}<Copy size={18}/></button><input className="credential" type="password" readOnly value={recovery} aria-label="Private recovery key"/></details>}
 </>}
 {tab==='Requests'&&<><p className="page-description">Quote requests from your connected node. Review the request and contact the customer directly.</p>{b.quotes.length===0?<section className="empty-state"><span className="empty-icon"><MessageSquare size={36}/></span><h2>Room for your next customer.</h2><p>When an agent sends a quote request, you’ll find it here. Nothing has arrived yet.</p></section>:<div className="request-list">{[...b.quotes].reverse().map(quote=><article className="request-card" key={quote.id}><div className="section-heading"><h2>{quote.name}</h2><Status>Received</Status></div><p>{quote.request}</p><div className="request-footer"><time dateTime={quote.createdAt}>{new Date(quote.createdAt).toLocaleString()}</time><a className="button secondary" href={`mailto:${quote.email}`}>Email customer <Mail size={18}/></a></div><details><summary>Request details <ChevronDown size={16}/></summary><span>{quote.email}</span><code>{quote.id}</code></details></article>)}</div>}
 <details className="disclosure" key="quote-test"><summary>Check that requests reach you <ChevronDown size={18}/></summary><p>Send a real test request into this inbox. It is stored and counted in your activity. No email is sent and no price is promised.</p>{!published?<button className="button secondary" onClick={()=>navigate('Home')}>Finish setup <ArrowRight size={18}/></button>:<form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);run('quote',async()=>{const receipt=await api<Receipt>('/api/call',{action:'request_quote',input:{name:fd.get('name'),email:fd.get('email'),request:fd.get('request')}});setResult(receipt);form.reset()},'Request received. It is saved in your inbox.')}}><div className="form-grid"><label className="field">Name<input name="name" placeholder="Your name (test)" required maxLength={120}/></label><label className="field">Email<input name="email" type="email" required/></label></div><label className="field">Request<textarea name="request" required minLength={5} maxLength={3000} placeholder="Test request: I’d like to know more about…"/></label><button className="button primary" disabled={!!busy}>{busy==='quote'?<Busy/>:<>Send test request <ArrowRight size={18}/></>}</button></form>}</details></>}
 {tab==='Business'&&<><section className="business-editor"><p className="page-description">The details agents use to help people find you.</p><form onSubmit={(e:FormEvent)=>{e.preventDefault();run('save',()=>api(imported?'/api/surface':'/api/ingest',imported?edit:{details:edit},imported?'PATCH':'POST'),imported?'Business details saved.':'Business connected. Go to Home to review and activate.')}}>{field('name','Business name')}<label className="field">Services<span className="field-hint">One service per line</span><textarea rows={4} value={(edit.services||[]).join('\n')} onChange={e=>setEdit({...edit,services:e.target.value.split('\n')})} placeholder={'Haircut\nColour consultation'}/></label><label className="field">About your business<textarea value={edit.description||''} onChange={e=>setEdit({...edit,description:e.target.value})}/></label><div className="form-grid">{field('category','Business type')}{field('address','Address')}</div><details className="disclosure"><summary>Contact details & opening hours <ChevronDown size={18}/></summary><div className="form-grid">{field('website','Website','url')}{field('phone','Phone','tel')}{field('email','Email','email')}{field('timezone','Timezone')}</div>{field('hours','Opening hours')}</details><div className="save-row"><button className="button primary" disabled={!!busy}>{busy==='save'?<Busy/>:<>Save details <Check size={18}/></>}</button>{imported&&!published&&<button type="button" className="text-button" onClick={()=>navigate('Home')}>Review & activate <ArrowRight size={18}/></button>}</div></form>{imported&&<p className="fine-print">Imported from {b.surface.source} · {b.surface.confidence} confidence. Check details for accuracy.</p>}</section>
 <details className="disclosure" key="connection"><summary><span><Code2 size={19}/> Agent connection</span><ChevronDown size={18}/></summary><p>Your hosted REST node lets authorized agents find your business and send requests.</p>{[['Node URL',w.nodeUrl],['REST endpoint',w.apiUrl],['OpenAPI schema',w.schemaUrl]].map(([label,value])=><label className="field" key={label}>{label}<div className="copy-field"><input readOnly value={value}/><button type="button" className="button secondary" aria-label={`Copy ${label}`} onClick={()=>copy(value,label)}>{copied===label?<Check size={18}/>:<Copy size={18}/>}</button></div></label>)}<a className="text-button" href={w.schemaUrl} target="_blank" rel="noreferrer">Open API schema <ArrowUpRight size={18}/></a><h3>Caller key</h3><p>A key authorizes access. Creating a new one revokes the previous key. Save it securely; it is shown once.</p><button className="button secondary" disabled={!!busy} onClick={()=>run('key',async()=>{const data=await api<{key:string}>('/api/caller-key',{});setKey(data.key)})}>{busy==='key'?<Busy/>:w.hasCallerKey?'Replace caller key':'Create caller key'}</button>{key&&<label className="field">New caller key<div className="copy-field"><input type="password" readOnly value={key}/><button className="button secondary" onClick={()=>copy(key,'key')}>{copied==='key'?'Copied':'Copy'}</button></div></label>}</details>
 <details className="disclosure" key="activity"><summary>Connection activity <ChevronDown size={18}/></summary><p>{w.funnel.timeToCallableMs===null?'No successful call yet.':`First successful call after ${Math.round(w.funnel.timeToCallableMs/1000)} seconds.`}</p><div className="event-list">{[...b.events].reverse().map(e=><div className="event-row" key={e.id}><div><strong>{e.name.replaceAll('_',' ')}</strong>{e.reason&&<span>{e.reason}</span>}<code>{e.business_id}</code></div><time dateTime={e.timestamp}>{new Date(e.timestamp).toLocaleString()}</time></div>)}</div></details>
 <details className="disclosure"><summary>Recovery & keep-alive <ChevronDown size={18}/></summary>{recovery?<><p>Keep your private recovery key somewhere safe.</p><div className="copy-field"><input type="password" readOnly value={recovery} aria-label="Recovery key"/><button className="button secondary" onClick={()=>copy(recovery,'recovery')}>{copied==='recovery'?'Copied':'Copy key'}</button></div></>:<p>Your recovery key was shown when you created this workspace. It cannot be retrieved again.</p>}<p>Refresh due {new Date(b.refresh.nextDueAt).toLocaleDateString()}. This MVP includes a scheduled placeholder; automatic updates are not enabled.</p></details></>}
 <footer className="workspace-footer"><span>Agent Power Up</span><span>Your business. Open to what’s next.</span></footer></main><div className="mobile-nav">{nav}</div></div>
}

export function Access(){const[key,setKey]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');return <main className="center-screen"><Brand/><h1>Welcome back.</h1><p>Use your private recovery key to reopen your business.</p><form className="access-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/api/restore',{recoveryKey:key});window.location.href='/builder'}catch(err){setError((err as Error).message);setBusy(false)}}}><label className="field">Recovery key<input type="password" value={key} onChange={e=>setKey(e.target.value)} required autoComplete="off"/></label><button className="button primary" disabled={busy}>{busy?<Busy/>:<>Open my business <ArrowRight size={20}/></>}</button>{error&&<p className="error" role="alert">{error}</p>}</form><Link className="text-button" href="/builder">Open this browser’s workspace</Link><Link className="text-button" href="/"><ArrowLeft size={17}/> Start free</Link></main>}
